### ISSUE TITLE
bosh-cli bash-completion breaks file bash-completion

### ISSUE THREAD

**Issue by loewenstein** [cloudfoundry/homebrew-tap#28]
- `brew install bosh-cli`
- `touch bosh-init.yml`
- `bosh2 create-env bo` <TAB>

Nothing happens although there is a file `bosh-init.yml`

**Comment by voelzmo** [comment]
Workaround for now: manually remove `/usr/local/etc/bash_completion.d/bosh-cli`

**Comment by dkoper** [comment]
FWIW, we had a similar problem with the cf CLI.
Although we addressed it in code (explicitly implement a filepath completer for all relevant arguments), there may also be a one-line fix in the completion file (adding `-o default` to the `complete` command?).
Take care with the flags to `complete`, some are not available on all distributions and Bash versions.

**Comment by friegger** [comment]
@dkoper Are you aware of `-o default` not being available somewhere? Why did you decide to implement a filepath completer instead? It is only roughly behaving like regular bash folder and file completion. For instance, completing a folder always adds a space after the slash and one has to delete the space in order to continue completion in the folder.

**Comment by dkoper** [comment]
@friegger We found the `-o default` flag after we implemented the filepath completer. I can't find the statement anymore about it not being available. Maybe it related to `-o bashdefault` with pre-4.0 Bash but honestly, no idea..

**Comment by dpb587-pivotal** [comment]
Closing - seems like this was fixed as part of cloudfoundry/bosh-cli#361.
